### ISSUE TITLE
subtitile mistake in JIT and AOT advanteges section

### ISSUE THREAD

**Issue by sandeepsaini309** [manthanank/learn-angular#48]
in the subtitle of JIT and AOT Advantages section
subtitles are misplaced

'Advantages of AOT' instead of 'Advantages of JIT'
and 'Advantages of JIT' instead of 'Advantages of AOT'

![image](https://github.com/manthanank/learn-angular/assets/72447278/45019084-a72d-4990-b0cd-5eda5cfbcc35)

**Comment by manthanank** [comment]
Updated

**Comment by manthanank** [comment]
Updated
